import { Inter } from 'next/font/google';
import './globals.css';
import RecoilProvider from './recoil/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center items-center`}>
        <RecoilProvider>{children}</RecoilProvider>
      </body>
    </html>
  );
};

export default RootLayout;
